# Generated by Django 4.2.5 on 2023-09-28 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="username",
            field=models.CharField(
                default="<function uuid4 at 0x10553f7e0>",
                max_length=100,
                primary_key=True,
                serialize=False,
                unique=True,
                verbose_name="username",
            ),
        ),
    ]
