# Generated by Django 4.2.7 on 2024-04-04 17:42

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0003_alter_institution_expires_alter_user_username"),
    ]

    operations = [
        migrations.AlterField(
            model_name="institution",
            name="expires",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2024, 7, 13, 17, 42, 48, 891431, tzinfo=datetime.timezone.utc
                )
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="username",
            field=models.CharField(
                default="a41ebc1c-8340-42d4-900c-37e3e866a1d6",
                max_length=100,
                primary_key=True,
                serialize=False,
                unique=True,
                verbose_name="username",
            ),
        ),
    ]
