# Generated by Django 4.2.5 on 2023-09-28 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0003_alter_user_username"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="username",
            field=models.CharField(
                default="904367fd-875f-4ac5-aa36-c895303d329a",
                max_length=100,
                primary_key=True,
                serialize=False,
                unique=True,
                verbose_name="username",
            ),
        ),
    ]
