# Generated by Django 4.2.7 on 2024-04-10 07:27

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0004_alter_institution_expires_alter_user_username"),
    ]

    operations = [
        migrations.AlterField(
            model_name="institution",
            name="expires",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2024, 7, 19, 7, 27, 56, 656395, tzinfo=datetime.timezone.utc
                )
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="username",
            field=models.CharField(
                default="f35a5a03-49b7-4c2c-b386-f713abccef88",
                max_length=100,
                primary_key=True,
                serialize=False,
                unique=True,
                verbose_name="username",
            ),
        ),
    ]
