# Generated by Django 4.2.5 on 2023-09-29 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0004_alter_user_username"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="age_group",
            field=models.CharField(
                choices=[
                    ("AG0", "?"),
                    ("AG1", "<12"),
                    ("AG2", "12-17"),
                    ("AG3", "18-25"),
                    ("AG4", "26-35"),
                    ("AG5", "36-50"),
                    ("AG6", "51-70"),
                    ("AG7", ">70"),
                ],
                default="AG0",
                max_length=3,
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="avatar",
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="user",
            name="username",
            field=models.CharField(
                default="421e5e55-928d-4306-85d0-48257c48813b",
                max_length=100,
                primary_key=True,
                serialize=False,
                unique=True,
                verbose_name="username",
            ),
        ),
    ]
