# Generated by Django 4.2.7 on 2024-04-11 06:56

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0005_alter_institution_expires_alter_user_username"),
    ]

    operations = [
        migrations.AlterField(
            model_name="institution",
            name="expires",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2024, 7, 20, 6, 56, 16, 797175, tzinfo=datetime.timezone.utc
                )
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="username",
            field=models.CharField(
                default="5ebe092f-fbd5-4d07-afe4-5cd412e5f44c",
                max_length=100,
                primary_key=True,
                serialize=False,
                unique=True,
                verbose_name="username",
            ),
        ),
    ]
