# Generated by Django 4.2.5 on 2023-10-08 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0006_alter_user_username"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="geolocation",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="user",
            name="username",
            field=models.CharField(
                default="2970ef9b-a584-4204-bbdf-721244c26238",
                max_length=100,
                primary_key=True,
                serialize=False,
                unique=True,
                verbose_name="username",
            ),
        ),
    ]
