# Generated by Django 4.2.7 on 2024-04-12 05:54

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0007_alter_institution_expires_alter_user_username"),
    ]

    operations = [
        migrations.AlterField(
            model_name="institution",
            name="expires",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2024, 7, 21, 5, 54, 29, 931383, tzinfo=datetime.timezone.utc
                )
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="username",
            field=models.CharField(
                default="cf7b5f8a-d5f2-4f26-ba1d-eed9f0e9b791",
                max_length=100,
                primary_key=True,
                serialize=False,
                unique=True,
                verbose_name="username",
            ),
        ),
    ]
