# Generated by Django 4.2.5 on 2023-10-17 13:52

from django.db import migrations, models
import users.models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0010_alter_user_username"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="avatar_img",
            field=models.ImageField(
                blank=True,
                null=True,
                storage=users.models.OverwriteStorage,
                upload_to="avatars/",
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="username",
            field=models.CharField(
                default="ef6fe679-c1a1-4ca9-8c88-60e5c3222de9",
                max_length=100,
                primary_key=True,
                serialize=False,
                unique=True,
                verbose_name="username",
            ),
        ),
    ]
