# Generated by Django 5.0.4 on 2024-07-21 07:32

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0011_alter_institution_expires_alter_user_username"),
    ]

    operations = [
        migrations.AlterField(
            model_name="institution",
            name="expires",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2024, 10, 29, 7, 32, 24, 465458, tzinfo=datetime.timezone.utc
                )
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="username",
            field=models.CharField(
                default="b0bde7aa-4548-4f9c-987d-aaf838fe35e5",
                max_length=100,
                primary_key=True,
                serialize=False,
                unique=True,
                verbose_name="username",
            ),
        ),
    ]
