FROM runsascoded/geopandas
RUN apt-get update && apt-get install -y libpq-dev gcc python3-dev musl-dev ffmpeg libsm6 libxext6
ENV PATH=/usr/bin:$PATH

RUN mkdir /code
WORKDIR /code
ADD requirements.txt /code/
RUN pip install -r requirements.txt
ADD ./ /code/