# Generated by Django 4.2.7 on 2024-03-22 12:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("datastore", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="survey",
            name="owner",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="my_survey",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="survey",
            name="sharedwith",
            field=models.ManyToManyField(
                related_name="survey", to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AddField(
            model_name="patientdata",
            name="cellparent",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="cell_content",
                to="datastore.celldata",
            ),
        ),
        migrations.AddField(
            model_name="patientdata",
            name="owner",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="my_patientdata",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="patientdata",
            name="sharedwith",
            field=models.ManyToManyField(
                related_name="patientdata", to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AddField(
            model_name="celldata",
            name="owner",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="my_celldata",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="celldata",
            name="owner_institution",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="celldata",
                to="users.institution",
            ),
        ),
    ]
