# Generated by Django 4.2.7 on 2024-03-23 06:53

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("datastore", "0002_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="patientdata",
            name="sharedwith",
        ),
        migrations.AddField(
            model_name="celldata",
            name="sharedwith",
            field=models.ManyToManyField(
                related_name="celldata", to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
