# Generated by Django 4.2.5 on 2023-10-15 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("datastore", "0002_alter_patientdata_owner_alter_patientdata_type_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="survey",
            name="score",
            field=models.SmallIntegerField(default=0),
        ),
    ]
