# Generated by Django 4.2.7 on 2024-03-23 09:26

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("datastore", "0003_remove_patientdata_sharedwith_celldata_sharedwith"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="survey",
            name="sharedwith",
        ),
        migrations.AlterField(
            model_name="celldata",
            name="sharedwith",
            field=models.ManyToManyField(
                blank=True,
                null=True,
                related_name="celldata",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
