# Generated by Django 4.2.7 on 2023-11-19 07:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("datastore", "0004_alter_patientdata_owner_alter_survey_owner"),
    ]

    operations = [
        migrations.CreateModel(
            name="SurveyObjection",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("data", models.JSONField(blank=True, null=True)),
                (
                    "related_survey",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="objection",
                        to="datastore.survey",
                    ),
                ),
            ],
        ),
    ]
