# Generated by Django 4.2.7 on 2024-04-04 17:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("datastore", "0004_remove_survey_sharedwith_alter_celldata_sharedwith"),
    ]

    operations = [
        migrations.AddField(
            model_name="patientdata",
            name="redirect",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name="survey",
            name="redirect",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name="patientdata",
            name="cellparent",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="cell_content",
                to="datastore.celldata",
            ),
        ),
    ]
