# Generated by Django 4.2.7 on 2024-04-10 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("datastore", "0005_patientdata_redirect_survey_redirect_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="celldata",
            name="icf_store",
            field=models.JSONField(blank=True, null=True),
        ),
    ]
