# Generated by Django 4.2.7 on 2024-04-11 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("datastore", "0006_celldata_icf_store"),
    ]

    operations = [
        migrations.AddField(
            model_name="celldata",
            name="status",
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
