# Generated by Django 4.2.7 on 2024-04-11 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("datastore", "0007_celldata_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="celldata",
            name="status",
            field=models.CharField(default="open", max_length=10),
        ),
    ]
