# Generated by Django 4.2.7 on 2024-04-12 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("datastore", "0008_alter_celldata_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="patientdata",
            name="redirect",
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name="survey",
            name="redirect",
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
