# Generated by Django 4.2.7 on 2024-04-13 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("datastore", "0009_alter_patientdata_redirect_alter_survey_redirect"),
    ]

    operations = [
        migrations.AddField(
            model_name="survey",
            name="status",
            field=models.SmallIntegerField(default=0),
        ),
    ]
