# Generated by Django 5.0.4 on 2024-04-20 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("datastore", "0010_survey_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="patientdata",
            name="redirect_id",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="survey",
            name="redirect_id",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
