# Generated by Django 5.0.4 on 2024-07-21 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("datastore", "0011_patientdata_redirect_id_survey_redirect_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="celldata",
            name="data_handling",
            field=models.CharField(
                choices=[("SEPARATE", "SEPARATE"), ("MERGE", "MERGE")],
                default="SEPARATE",
                max_length=10,
            ),
        ),
    ]
